### ISSUE TITLE
Manifest file formatting error

### ISSUE THREAD

**Issue by iandees** [iandees/josm-mbtiles#15]
As reported by a JOSM user here: https://josm.openstreetmap.de/ticket/15205

I ran into this before, but don't remember what I did to fix the problem. From my inspection of the jar file, it seems that the manfiest file is formatted properly. I haven't been able to get my local JOSM to update the mbtiles plugin automatically so I can't reproduce this yet.

**Comment by don-vip** [comment]
You have an empty line just after "Plugin-Date". The git command probably includes a newline at the end, it should be escaped.

**Comment by iandees** [comment]
Thanks!

**Comment by iandees** [comment]
I manually adjusted the manifest and reuploaded the JAR for now.

@floscher I wonder if you could look at the changes I made in https://github.com/iandees/josm-mbtiles/commit/a63495284700effee2e4d4a54724fc20315c4648 and suggest a way to add the contents of the sqlite JDBC JAR to the output JAR. I tried a few things and read some docs but haven't been able to figure it out.

**Comment by floscher** [comment]
@iandees Sure, I'll have a look into it. Great to see the plugin is already useful for somebody! :tada:

In the past few days I continued development on the `gradle-josm-plugin` and made it easier to apply it to JOSM plugins. I'll prepare a pull request for upgrading to `v0.1.4` or later of the `gradle-josm-plugin`, which will shorten your `build.gradle` file, eliminate the `manifest.gradle` file and hopefully it will solve the issue.

A PR for josm-fieldpapers should also be incoming soon, now that I'm back from vacation.

**Comment by floscher** [comment]
I wasn't able to reproduce the Manifest formatting error. Is this in the Ant build or the Gradle build?

Dependencies can now be added to the release JAR by using the configuration `packIntoJar`, which is part of `gradle-josm-plugin` since `v0.1.5` (released earlier today).

**Comment by iandees** [comment]
The manifest format error was fixed as part of switching to Gradle ([the Ant build step that generated the plugin date](https://github.com/iandees/josm-mbtiles/blob/6d51c28350954488e15ddf78811667f98aefd4ee/build.xml#L69-L74) pulled in a newline). Thanks for releasing an update!
