### ISSUE TITLE
support pmtiles

### ISSUE THREAD

**Issue by RobJN** [iandees/josm-mbtiles#22]
See: https://protomaps.com/docs/pmtiles

Adding support would be useful for those who'd like to adopt the new format for the reasons explained on their site.

Thanks for considering this request.
Rob

**Comment by bdon** [comment]
It has some overlap with https://github.com/onthegomap/planetiler/issues/98 which may eventually get extracted into a standalone Java package. Some parts of JOSM package that may be relevant are:

* if JOSM provides functions for doing compression/decompression (GZIP at minimum)
* functions for HTTP requests or even signed requests with an awsv4 Authorization header
* whether to support read-only pmtiles (not writing) and whether it needs only a set tiles for display or more advanced tasks like listing all tiles

**Comment by bdon** [comment]
@tsmock cool! most of the Java related code for pmtiles right now lives here: 
https://github.com/onthegomap/planetiler/blob/main/planetiler-core/src/main/java/com/onthegomap/planetiler/pmtiles/

**Comment by tsmock** [comment]
I already wrote the reading implementation. And debugged it.

Have a screenshot (you probably recognize it -- I was testing against the test files in the specification directory):
<img width="1232" alt="image" src="https://github.com/iandees/josm-mbtiles/assets/45215054/9aa713c4-39de-4ad1-86cf-bbb27f740af5">

**Comment by iandees** [comment]
@tsmock Do you want to link to your pmtiles plugin here?

**Comment by tsmock** [comment]
Sure: https://josm.openstreetmap.de/browser/osm/applications/editors/josm/plugins/pmtiles
It is available in the JOSM plugin list.

**Comment by iandees** [comment]
Nice, thanks.
