### ISSUE TITLE
Min zoom level of 0 not accepted

### ISSUE THREAD

**Issue by aharfoot** [iandees/josm-mbtiles#4]
I believe that a zoom level of 0 is valid - this is a single tile that covers the whole world. However, in the MbtilesLayer.java code, the metadata validation as it currently stands will not accept minzoom=0. Could this be adjusted?

**Comment by homme** [comment]
@iandees Can you tell us why this has been closed?

**Comment by iandees** [comment]
Closed by accident. I'll reopen when I get home.

**Comment by homme** [comment]
Thanks!

**Comment by iandees** [comment]
Is this still a problem? I don't see any validation code that would cause breakage when the minzoom is zero.

**Comment by aharfoot** [comment]
Hi Ian,

I see that you removed the validation lines in your 'Get it running again' commit. The line
if (name == null || maxz == 0 || minz == 0 || bounds == null)

was the offending one, and now it has been removed the problem should have been fixed, but I am unable to test this at the moment. I'll let you know when I have.

Cheers,

Andy

--

Andy Harfoot

GeoData Institute
University of Southampton
Southampton
SO17 1BJ

Tel:  +44 (0)23 8059 2719
Fax:  +44 (0)23 8059 2849

www.geodata.soton.ac.uk
________________________________

**Comment by iandees** [comment]
Ah, cool. I don't have an mbtiles to test with either. I'll leave this open a few more days. Let me know if someone is able to test it please.

**Comment by aharfoot** [comment]
This is fixed.
