### ISSUE TITLE
Opening an mbtiles file has stopped working between JOSM 8159 and 8279

### ISSUE THREAD

**Issue by PaulUithol** [iandees/josm-mbtiles#5]
Loading mbtiles files seems to have stopped working between JOSM version 8159 and 8279. This seems to be true for all mbtiles files; I've tried about four, on two different machines (one completely clean install).

1. Open an mbtiles files
2. Expected result: a layer with the mbtiles file. Actual result: nothing at all.

This is still true for the latest dev version, 8465. Is there any log or debug output I could help you gather to work on a fix?

**Comment by iandees** [comment]
It would help to know what the error message is. I run JOSM from the command line, so if you do the same you can see the error message in the console that you started it from.

**Comment by PaulUithol** [comment]
There's no error message. Just this (and no layer :)

```
INFO: GET https://api.openstreetmap.org/api/0.6/user/details (get number of unread messages)
INFO: GET https://api.openstreetmap.org/api/0.6/map?bbox=39.2407608,-6.8407036,39.2515755,-6.8335451
INFO: Open file: D:\Downloads\buguruni-sw.mbtiles (1294409728 bytes)
[INFO] IndexedDiskCache - Region [TMS] Cache file root directory: C:\Users\Paul\AppData\Local\JOSM\cache\tms
[INFO] IndexedDiskCache - Region [TMS] Set maxKeySize to: '25000'
[INFO] IndexedDiskCache - Region [TMS] Loaded keys from [TMS], key count: 16; up to 25000 will be available.
[INFO] IndexedDiskCache - Region [TMS] Finished inital consistency check, isOk = true in 0ms.
[INFO] IndexedDiskCache - Region [TMS] Indexed Disk Cache is alive.
```

**Comment by drkludge** [comment]
There was a change to the tile cache scheme.  That may be the place to look.  Whereas mbtiles is a cache and does not need to be cached yet again, the changes make have broken the plugin.

**Comment by iandees** [comment]
Ah, interesting. It's been a long while since I wrote this and don't have a JOSM dev environment set up. It'll be a week or two before I get a chance to get that set up again.

**Comment by animaux** [comment]
Any news on this? I’m in desperate need to have this working again. If I can help in any way, let me know.

**Comment by iandees** [comment]
I took a couple hours trying to get this going again but can't seem to quickly figure out how to hack around JOSM's new image caching mechanism. I'll try looking at it a bit more later.

**Comment by animaux** [comment]
Many thanks for looking into this!

**Comment by animaux** [comment]
Is there a way to motivate you into making this work again? Donations? Beer? Glory? :)

**Comment by batje** [comment]
A pat on the back perhaps?

**Comment by iandees** [comment]
I just published mbtiles.jar 2.0, which should work on more recent versions of JOSM. I'm going to close this but please try it out and file new tickets if you run into problems.

**Comment by drkludge** [comment]
On Wed, Nov 18, 2015 at 7:06 PM, Ian Dees <notifications@github.com> wrote:

> I just published mbtiles.jar 2.0, which should work on more recent
> versions of JOSM. I'm going to close this but please try it out and file
> new tickets if you run into problems.
>

Thank you!  I updated to 2.0 and restarted.  I ran a number of mbtiles
files with JOSM Version 8969 Last change at 2015-10-29 22:15:23 +0100 (Thu,
29 Oct 2015).  All features are working as far as I can tell.

**Comment by animaux** [comment]
Wow! The pat on the back did the trick! Seriously, ∞ thanks!

**Comment by PaulUithol** [comment]
Works fine for us indeed, thanks! Guys in Dar have been upgrading, good to be able to use nice things like the integrated Overpass download now :)
