### ISSUE TITLE
The plugin binary is not java 7 compatible

### ISSUE THREAD

**Issue by vramirez122000** [iandees/josm-mbtiles#7]
After I download and install the repository binaries, I am no longer able to run JOSM using a Java 7 Runtime because of the error: java.lang.UnsupportedClassVersionError: org/openstreetmap/josm/plugins/mbtiles/MbtilesPlugin : Unsupported major.minor version 52.0

Since the minimum requirements form JOSM are Java 7, this plugin should be built for that version.

**Comment by iandees** [comment]
Hmm, which version of the plugin do you have? I'm pretty sure I fixed this over in #6.

**Comment by vramirez122000** [comment]
Apparently, the issue is with deployment. I manually deleted the problematic jar file from .josm/plugins in order to force JOSM to redownload and, alas, the problem was solved. I suggest incrementing the plugin version in the manifest. Thanks for the quick response.
